writebook/config/routes.rb
Rails.application.routes.draw do
  root "books#index"

  resource :first_run, only: %i[ show create ]

  resource :session, only: %i[ new create destroy ] do
    scope module: "sessions" do
      resources :transfers, only: %i[ show update ]
    end
  end

  get "join/:join_code", to: "users#new", as: :join
  post "join/:join_code", to: "users#create"

  resource :account do
    scope module: "accounts" do
      resource :join_code, only: :create
      resource :custom_styles, only: %i[ edit update ]
    end
  end

  resources :books, except: %i[ index show ] do
    resource :publication, controller: "books/publications", only: %i[ show edit update ]
    resource :bookmark, controller: "books/bookmarks", only: :show

    scope module: "books" do
      namespace :leaves do
        resources :moves, only: :create
      end

      resource :search
    end

    resources :sections
    resources :pictures
    resources :pages
  end

  get "/:id/:slug", to: "books#show", constraints: { id: /\d+/ }, as: :slugged_book
  get "/:book_id/:book_slug/:id/:slug", to: "leafables#show", constraints: { book_id: /\d+/, id: /\d+/ }, as: :slugged_leafable

  direct :book_slug do |book, options|
    route_for :slugged_book, book, book.slug, options
  end

  direct :leafable_slug do |leaf, options|
    route_for :slugged_leafable, leaf.book, leaf.book.slug, leaf, leaf.slug, options
  end

  resources :pages, only: [] do
    scope module: "pages" do
      resources :edits, only: :show
    end
  end

  resources :qr_code, only: :show
  resources :users do
    scope module: "users" do
      resource :profile
    end
  end

  direct :leafable do |leaf, options|
    route_for "book_#{leaf.leafable_name}", leaf.book, leaf, options
  end

  direct :edit_leafable do |leaf, options|
    route_for "edit_book_#{leaf.leafable_name}", leaf.book, leaf, options
  end

  namespace :action_text, path: nil do
    get "/u/*slug" => "markdown/uploads#show", as: :markdown_upload
    post "/uploads" => "markdown/uploads#create", as: :markdown_uploads
  end

  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

writebook/app/models/book.rb
class Book < ApplicationRecord
  include Accessable, Sluggable

  has_many :leaves, dependent: :destroy
  has_one_attached :cover, dependent: :purge_later

  scope :ordered, -> { order(:title) }
  scope :published, -> { where(published: true) }

  enum :theme, %w[ black blue green magenta orange violet white ].index_by(&:itself), suffix: true, default: :blue

  def press(leafable, leaf_params)
    leaves.create! leaf_params.merge(leafable: leafable)
  end
end

writebook/app/models/book/accessable.rb
module Book::Accessable
  extend ActiveSupport::Concern

  included do
    has_many :accesses, dependent: :destroy
    scope :with_everyone_access, -> { where(everyone_access: true) }
  end

  class_methods do
    def accessable_or_published(user: Current.user)
      if user.present?
        accessable_or_published_books
      else
        published
      end
    end

    def accessable_or_published_books(user: Current.user)
      user.books.or(published).distinct
    end
  end

  def accessable?(user: Current.user)
    accesses.exists?(user: user)
  end

  def editable?(user: Current.user)
    access_for(user: user)&.editor? || user&.administrator?
  end

  def access_for(user: Current.user)
    accesses.find_by(user: user)
  end

  def update_access(editors:, readers:)
    editors = Set.new(editors)
    readers = Set.new(everyone_access? ? User.active.ids : readers)

    all = editors + readers
    all_accesses = all.collect { |user_id|
      { user_id: user_id, level: editors.include?(user_id) ? :editor : :reader }
    }

    accesses.upsert_all(all_accesses, unique_by: [ :book_id, :user_id ])
    accesses.where.not(user_id: all).delete_all
  end
end

writebook/app/models/book/sluggable.rb
module Book::Sluggable
  extend ActiveSupport::Concern

  included do
    before_save :generate_slug, if: -> { slug.blank? }
  end

  def generate_slug
    self.slug = title.parameterize
  end
end

writebook/app/controllers/books/bookmarks_controller.rb
class Books::BookmarksController < ApplicationController
  allow_unauthenticated_access

  include BookScoped

  def show
    @leaf = @book.leaves.active.find_by(id: last_read_leaf_id) if last_read_leaf_id.present?
  end

  private
    def last_read_leaf_id
      cookies["reading_progress_#{@book.id}"]
    end
end

writebook/app/controllers/books/leaves/moves_controller.rb
class Books::Leaves::MovesController < ApplicationController
  include BookScoped

  before_action :ensure_editable

  def create
    leaf, *followed_by = leaves
    leaf.move_to_position(position, followed_by: followed_by)
  end

  private
    def position
      params[:position].to_i
    end

    def leaves
      @book.leaves.find(Array(params[:id]))
    end
end

writebook/app/controllers/books/publications_controller.rb
class Books::PublicationsController < ApplicationController
  include BookScoped

  before_action :ensure_editable, only: %i[ edit update ]

  def show
  end

  def edit
  end

  def update
    @book.update! book_params
    redirect_to book_slug_url(@book)
  end

  private
    def book_params
      params.require(:book).permit(:published, :slug)
    end
end

writebook/app/controllers/books/searches_controller.rb
class Books::SearchesController < ApplicationController
  allow_unauthenticated_access

  include BookScoped

  def create
    @leaves = @book.leaves.active.search(params[:search]).favoring_title.limit(50)
  end
end

writebook/app/controllers/books_controller.rb
class BooksController < ApplicationController
  allow_unauthenticated_access only: %i[ index show ]

  before_action :ensure_index_is_not_empty, only: :index
  before_action :set_book, only: %i[ show edit update destroy ]
  before_action :set_users, only: %i[ new edit ]
  before_action :ensure_editable, only: %i[ edit update destroy ]

  def index
    @books = Book.accessable_or_published.ordered
  end

  def new
    @book = Book.new
  end

  def create
    book = Book.create! book_params
    update_accesses(book)

    redirect_to book_slug_url(book)
  end

  def show
    @leaves = @book.leaves.active.with_leafables.positioned
  end

  def edit
  end

  def update
    @book.update(book_params)
    update_accesses(@book)
    remove_cover if params[:remove_cover] == "true"

    redirect_to book_slug_url(@book)
  end

  def destroy
    @book.destroy

    redirect_to root_url
  end

  private
    def set_book
      @book = Book.accessable_or_published.find params[:id]
    end

    def set_users
      @users = User.active.ordered
    end

    def ensure_editable
      head :forbidden unless @book.editable?
    end

    def ensure_index_is_not_empty
      if !signed_in? && Book.published.none?
        require_authentication
      end
    end

    def book_params
      params.require(:book).permit(:title, :subtitle, :author, :cover, :remove_cover, :everyone_access, :theme)
    end

    def update_accesses(book)
      editors = [ Current.user.id, *params[:editor_ids]&.map(&:to_i) ]
      readers = [ Current.user.id, *params[:reader_ids]&.map(&:to_i) ]

      book.update_access(editors: editors, readers: readers)
    end

    def remove_cover
      @book.cover.purge
    end
end

writebook/app/helpers/books/editing_helper.rb
module Books::EditingHelper
  def editing_mode_toggle_switch(leaf, checked:)
    target_url = checked ? leafable_slug_path(leaf) : edit_leafable_path(leaf)
    render "books/edit_mode", target_url: target_url, checked: checked
  end
end

writebook/app/helpers/books_helper.rb
module BooksHelper
  def book_toc_tag(book, &)
    tag.ol class: "toc", tabindex: 0,
      data: {
        controller: "arrangement",
        action: arrangement_actions,
        arrangement_cursor_class: "arrangement-cursor",
        arrangement_selected_class: "arrangement-selected",
        arrangement_placeholder_class: "arrangement-placeholder",
        arrangement_move_mode_class: "arrangement-move-mode",
        arrangement_url_value: book_leaves_moves_url(book)
      }, &
  end

  def book_part_create_button(book, kind, **, &)
    url = url_for [ book, kind.new ]

    button_to url, class: "btn btn--plain txt-medium fill-transparent disable-when-arranging disable-when-deleting", draggable: true,
      data: {
        action: "dragstart->arrangement#dragStartCreate dragend->arrangement#dragEndCreate",
        arrangement_url_param: url
      }, **, &
  end

  def link_to_first_leafable(leaves)
    if first_leaf = leaves.first
      link_to leafable_slug_path(first_leaf), data: hotkey_data_attributes("right"), class: "disable-when-arranging", hidden: true do
        tag.span(class: "btn") do
          image_tag("arrow-right.svg", aria: { hidden: true }, size: 24) + tag.span("Start reading", class: "for-screen-reader")
        end + tag.span(first_leaf.title, class: "overflow-ellipsis")
      end
    end
  end

  def link_to_previous_leafable(leaf, hotkey: true, for_edit: false)
    if previous_leaf = leaf.previous
      path = for_edit ? edit_leafable_path(previous_leaf) : leafable_slug_path(previous_leaf)
      link_to path, data: hotkey_data_attributes("left", enabled: hotkey), class: "btn" do
        image_tag("arrow-left.svg", aria: { hidden: true }, size: 24) + tag.span("Previous: #{ previous_leaf.title }", class: "for-screen-reader")
      end
    else
      link_to book_slug_path(leaf.book), data: hotkey_data_attributes("left", enabled: hotkey), class: "btn" do
        image_tag("arrow-left.svg", aria: { hidden: true }, size: 24) + tag.span("Table of contents: #{ leaf.book.title }", class: "for-screen-reader")
      end
    end
  end

  def link_to_next_leafable(leaf, hotkey: true, for_edit: false)
    if next_leaf = leaf.next
      path = for_edit ? edit_leafable_path(next_leaf) : leafable_slug_path(next_leaf)
      link_to path, data: hotkey_data_attributes("right", enabled: hotkey), class: "btn txt-medium min-width" do
        tag.span("Next: #{next_leaf.title }", class: "overflow-ellipsis") + image_tag("arrow-right.svg", aria: { hidden: true }, size: 24)
      end
    else
      link_to book_slug_path(leaf.book), data: hotkey_data_attributes("right", enabled: hotkey), class: "btn txt-medium" do
        tag.span("Table of contents: #{leaf.book.title }", class: "overflow-ellipsis") + image_tag("arrow-reverse.svg", aria: { hidden: true }, size: 24)
      end
    end
  end

  private
    def hotkey_data_attributes(key, enabled: true)
      if enabled
        { controller: "hotkey", action: "keydown.#{key}@document->hotkey#click touch:swipe-#{key}@window->hotkey#click" }
      end
    end
end

writebook/app/views/books/_book.html.erb
<% cache book do %>
  <figure class="library__book <%= "theme--#{book&.theme}" unless book.cover.attached? %>">
    <div class="flex flex-column gap-half">
      <div class="flex-inline position-relative center">
        <% if book.cover.attached? %>
          <%= image_tag book.cover, alt: "Book cover", class: "book__cover" %>
        <% else %>
          <span class="book__cover-wrapper">
            <%= image_tag "empty-cover.png", alt: "Book cover", class: "book__cover margin-block-none center" %>
            <span class="book__title overflow-line-clamp pad txt-align-start txt-tight-lines" style="--lines: 6" aria-hidden="true"><%= book.title %></span>
          </span>
        <% end %>
        <%= turbo_frame_tag dom_id(book, :bookmark), src: book_bookmark_path(book), target: "_top" %>
      </div>
      <h2 class="margin-none flex flex-column txt-normal txt-tight-lines txt-medium--responsive">
        <strong><%= book.title %></strong>
        <span class="overflow-line-clamp"><%= book.author %></span>
      </h2>
    </div>
  </figure>
<% end %>

writebook/app/views/books/_edit_mode.html.erb
<%= tag.div class: "flex align-center gap flex-item-no-shrink",
      data: {
        controller: "edit-mode",
        edit_mode_target_url_value: target_url,
        edit_mode_editing_class: "edit-mode",
        edit_mode_autosave_outlet: "[data-controller='autosave']",
      } do %>
  <%= image_tag "eye.svg", aria: { hidden: true }, size: 28, class: "colorize--black" %>
  <label class="switch txt-medium">
    <%= check_box_tag :edit_mode_enabled, checked: checked, class: "switch__input", data: { action: "edit-mode#change" } %>
    <span class="switch__btn round"></span>
    <span class="for-screen-reader">Editing mode</span>
  </label>
  <%= image_tag "write.svg", aria: { hidden: true }, size: 24, class: "colorize--black" %>
<% end %>

writebook/app/views/books/_index_link.html.erb
<%= link_to root_path, class: "btn borderless txt-small flex-item-no-shrink" do %>
  <%= image_tag "books.svg", aria: { label: "Books" }, size: 19, class: "colorize--black", alt: "Books" %>
  <span class="for-screen-reader">All books</span>
<% end %>

writebook/app/views/books/_mode_buttons.html.erb
<label class="btn arrange-mode__button txt-medium flex-item-justify-end disable-when-deleting disable-when-empty">
  <input type="checkbox" name="arrange-mode" id="arrange-mode" data-action="arrangement#setArrangeMode">
  <%= image_tag "rearrange.svg", aria: { hidden: true }, size: 24 %>
  <span class="for-screen-reader">Rearrange</span>
</label>

<label class="btn delete-mode__button txt-medium disable-when-arranging disable-when-empty">
  <input type="checkbox" id="delete-mode">
  <%= image_tag "minus.svg", aria: { hidden: true }, size: 24 %>
  <span class="for-screen-reader">Delete pages</span>
</label>

writebook/app/views/books/_new.html.erb
<figure class="library__book position-relative">
  <div class="library__book--empty center">
    <%= image_tag "empty-cover.png", alt: "Book cover", class: "book__cover" %>
    <span class="btn btn--positive center">
      <%= image_tag "add.svg", aria: { hidden: true }, size: 24 %>
      <span class="for-screen-reader"></span>
    </span>
  </div>
  <%= link_to new_book_path, class: "bookmark__link" do %>
    <span class="for-screen-reader">Create a new book</span>
  <% end %>
</figure>

writebook/app/views/books/edit.html.erb
<% content_for(:title) { "Edit #{@book.title}" } %>

<% content_for :header do %>
  <nav>
    <%= link_to book_slug_path(@book), class: "btn flex-item-justify-start" do %>
      <%= image_tag "arrow-left.svg", aria: { hidden: true }, size: 24 %>
      <span class="for-screen-reader">Cancel and go back</span>
    <% end %>
  </nav>
<% end %>

<%= render "books/form", book: @book, users: @users, creating_user: nil %>

<% content_for :footer do %>
  <nav class="flex align-end justify-center pad">
    <%= button_to book_path(@book), method: :delete, class: "btn btn--negative",
          data: { turbo_confirm: "Are you sure you want to delete this book? It cannot be undone." } do %>
      <%= image_tag "trash.svg", aria: { hidden: true }, size: 24 %>
      <span class="for-screen-reader">Delete <%= @book.title %></span>
    <% end %>
    <button type="submit" form="book-editor", class="new-book-btn btn btn--reversed center txt-medium--responsive" aria-label="Save changes" title="Save changes">
      <%= image_tag "check.svg", aria: { hidden: true }, size: 24 %>
    </button>
  </nav>
<% end %>

writebook/app/views/books/index.html.erb
<% content_for(:title) { "Library | Writebook" } %>
<% @layout_class = "books" %>

<% content_for :header do %>
  <nav>
    <span class="btn btn--placeholder" aria-hidden="true"></span>

    <a href="https://once.com/writebook" class="product__wordmark btn btn--plain txt-large center" target="_blank">
      <%= image_tag "writebook-icon.svg", aria: { hidden: true }, size: 24 %>
      <span>Writebook</span>
    </a>

    <% if Current.user %>
      <%= link_to users_path, class: "btn" do %>
        <%= image_tag "settings.svg", aria: { hidden: true }, size: 24 %>
        <span class="for-screen-reader">Manage people and settings</span>
      <% end %>
    <% else %>
      <%= link_to new_session_path, class: "btn" do %>
        <%= image_tag "login-keys.svg", aria: { hidden: true }, size: 24 %>
        <span class="for-screen-reader">Sign in</span>
      <% end %>
    <% end %>
  </nav>
<% end %>

<% cache [ @books, signed_in? ] do %>
  <div class="library">
    <%= render @books %>
    <%= render "books/new" if signed_in? %>
  </div>
<% end %>

writebook/app/views/books/new.html.erb
<% content_for(:title) { "Create a new book" } %>

<% content_for :header do %>
  <nav>
    <%= link_to root_path, class: "btn flex-item-justify-start" do %>
      <%= image_tag "arrow-left.svg", aria: { hidden: true }, size: 24 %>
      <span class="for-screen-reader">Cancel and go back</span>
    <% end %>
  </nav>
<% end %>

<%= render "books/form", book: @book, users: @users, creating_user: Current.user %>

<% content_for :footer do %>
  <nav class="new-book-btn flex justify-center pad">
    <button type="submit" form="book-editor", class="btn btn--reversed txt-medium--responsive" aria-label="Create book" title="Create book">
      <%= image_tag "arrow-right.svg", aria: { hidden: true }, size: 24 %>
    </button>
  </nav>
<% end %>

writebook/app/views/books/show.html.erb
<% content_for(:title) { @book.title } %>
<% @layout_class = "book" %>

<% content_for :head do %>
  <%= tag.meta property: "og:title", content: @book.title %>
  <%= tag.meta property: "og:description", content: @book.subtitle %>
  <%= tag.meta property: "og:image", content: @book.cover.blank? ? asset_url("covers/cover-#{@book.theme}-og.png") : "#{root_url}#{url_for(@book.cover)}" %>
  <%= tag.meta property: "og:url", content: book_slug_url(@book) %>

  <%= tag.meta property: "twitter:title", content: @book.title %>
  <%= tag.meta property: "twitter:description", content: @book.subtitle %>
  <%= tag.meta property: "twitter:image", content: @book.cover.blank? ? asset_url("covers/cover-#{@book.theme}-og.png") : "#{root_url}#{url_for(@book.cover)}" %>
  <%= tag.meta property: "twitter:card", content: "summary_large_image" %>
<% end %>

<% content_for :header do %>
  <nav class="book__navbar">
    <%= link_to root_path, class: "btn" do %>
      <%= image_tag "arrow-left.svg", aria: { hidden: true }, size: 24 %>
      <span class="for-screen-reader">Go back</span>
    <% end %>

    <span class="btn btn--placeholder placeholder-start" aria-hidden="true"></span>

    <div class="breadcrumbs">
      <%= render "books/index_link" %>
      <span class="flex-item-no-shrink">▸</span>
      <strong><%= @book.title %></strong>
    </div>

    <%= link_to_first_leafable(@leaves) %>

    <span class="btn btn--placeholder placeholder-end" aria-hidden="true"></span>

    <button class="btn fullscreen" data-action="fullscreen#toggle" data-fullscreen-target="button">
      <%= image_tag "expand.svg", aria: { hidden: true }, size: 24 %>
      <span class="for-screen-reader">Enter fullscreen</span>
    </button>

    <%= render "books/searches/search", book: @book %>

    <% if @book.editable? %>
      <%= link_to edit_book_path(@book), class: "btn settings" do %>
        <%= image_tag "settings.svg", aria: { hidden: true }, size: 24 %>
        <span class="for-screen-reader">Edit book settings</span>
      <% end %>
    <% end %>
  </nav>
<% end %>

<% cache [ @book, @book.editable? ] do %>
  <aside class="txt-align-center margin-block">
    <div class="book__sidebar <%= "theme--#{@book&.theme}" unless @book.cover.attached? %>">
      <% if @book.cover.attached? %>
        <%= link_to rails_blob_path(@book.cover, disposition: "attachment", only_path: true), data: { action: "lightbox#open:prevent", lightbox_target: "image", lightbox_url_value: rails_blob_path(@book.cover, disposition: "attachment", only_path: true) } do %>
          <%= image_tag @book.cover, alt: "Cover for #{ @book.title }", class: "book__cover margin-block-none center" %>
        <% end %>
      <% else %>
        <span class="book__cover-wrapper">
          <%= image_tag "empty-cover.png", alt: "Book cover", class: "book__cover margin-block-none center" %>
          <span class="book__title overflow-line-clamp pad txt-align-start txt-tight-lines"" style="--lines: 6" aria-hidden="true"><%= @book.title %></span>
        </span>
      <% end %>

      <% if @book.editable? %>
        <%= turbo_frame_tag @book, :publication do %>
          <%= render "books/publications/publication", book: @book %>
        <% end %>
      <% end %>

      <span data-controller="edit-mode" data-edit-mode-editing-class="edit-mode" />
    </div>
  </aside>

  <%= arrangement_tag @book, class: "arrangement__container toc__container full-width txt-align-center" do %>
    <h1 class="flex flex-column txt-tight-lines txt-align-start margin-block-end">
      <strong class="book__title txt-x-large--responsive"><%= @book.title %></strong>
      <span class="txt-large--responsive txt-normal"><%= @book.subtitle %></span>
      <span class="txt-large--responsive txt-normal"><%= @book.author %></span>
    </h1>

    <div class="book__toolbar fill-white flex gap-half pad-block margin-block-end-half justify-center <%= "position-sticky" if @book.editable? %>" data-controller="toc-view" data-toc-view-id-value="<%= dom_id(@book) %>">
      <label class="btn txt-medium disable-when-empty">
        <input type="radio" name="view" id="toc-list" value="list" data-toc-view-target="switch" data-toc-view-type-value="list" data-action="toc-view#saveViewPref">
        <%= image_tag "view-list.svg", aria: { hidden: true }, size: 24 %>
        <span class="for-screen-reader">List view</span>
      </label>

      <label class="btn txt-medium flex-item-justify-start disable-when-empty">
        <input type="radio" name="view" id="toc-grid" value="grid" checked="checked" data-toc-view-target="switch" data-toc-view-type-value="grid" data-action="toc-view#saveViewPref">
        <%= image_tag "view-grid.svg", aria: { hidden: true }, size: 24 %>
        <span class="for-screen-reader">Page view</span>
      </label>

      <% if @book.editable? %>
        <%= render "books/create_buttons", book: @book %>
        <%= render "books/mode_buttons", book: @book %>
      <% end %>
    </div>

    <div class="position-relative">
      <% if @book.editable? %>
        <div class="toc__blank-slate align-center justify-start">
          <%= image_tag "blank-slate-arrows.svg", aria: { hidden: true }, size: 60, class: "colorize--black" %>
          <span class="flex align-center gap-half"><span>🇺🇸</span> <span>Pick a page type to get started</span></span>
          <span class="flex align-center gap-half"><span>🇪🇸</span> <span>Elige un tipo de página para comenzar</span></span>
          <span class="flex align-center gap-half"><span>🇫🇷</span> <span>Choisissez un type de page pour commencer</span></span>
          <span class="flex align-center gap-half"><span>🇮🇳</span> <span>शुरू करने के लिए एक पृष्ठ प्रकार चुनें</span></span>
          <span class="flex align-center gap-half"><span>🇩🇪</span> <span>Wählen Sie einen Seitentyp, um zu beginnen</span></span>
          <span class="flex align-center gap-half"><span>🇧🇷</span> <span>Escolha um tipo de página para começar</span></span>
        </div>
      <% end %>

      <menu class="toc margin-none" tabindex="0" data-arrangement-target="container" data-action="<%= arrangement_actions %>">
        <%= turbo_frame_tag :leaves, data: { arrangement_target: "list" } do -%>
          <%= render partial: "leaves/leaf", collection: @leaves, as: :leaf -%>
        <% end -%>
      </menu>

      <div data-arrangement-target="layer" class="toc"></div>
      <div data-arrangement-target="dragImage" class="arrangement-drag-image"></div>
    </div>
  <% end %>
<% end %>

<% content_for :footer do %>
  <nav class="book__nav flex align-center justify-center">
    <a href="https://once.com/writebook" class="product__wordmark btn btn--plain txt-medium" target="_blank">
      <%= image_tag "writebook-icon.svg", aria: { hidden: true }, size: 24 %>
      <span>Made with Writebook</span>
    </a>
  </nav>
<% end %>